### ISSUE TITLE
Argument error

### ISSUE THREAD

**Issue by monting** [danielberkompas/cloak#57]
When I run `Cloak.encrypt("Hello")` , I'm getting:

```
** (ArgumentError) argument error
    (crypto) :crypto.aes_gcm_encrypt("some key", <<119, 173, 32, 108, 200, 173, 116, 55, 108, 205, 197, 110, 32, 104, 125, 54>>, "AES256GCM", "Hello", 16)
    (cloak) lib/cloak/ciphers/aes_gcm.ex:127: Cloak.AES.GCM.perform_encryption/3
    (cloak) lib/cloak.ex:161: Cloak.encrypt/2
```

My configuration:
```
config :cloak, Cloak.AES.GCM,
  tag: "AES",
  default: true,
  keys: [
    %{tag: <<1>>, key: System.get_env("CLOAK_KEY"), default: true}
  ]
```

I tried using CTR in the config as well, and was getting a similar Argument Error.

Erlang version: `20.1`
Elixir version: `1.6.2`

Any pointers appreciated!

**Comment by danielberkompas** [comment]
@monting As shown in the README, you need to `Base64.decode` your key before it can be used. (Assuming your key is in Base64 notation)

```
config :cloak, Cloak.AES.CTR,
  tag: "AES",
  default: true,
  keys: [
    %{tag: <<1>>, key: Base64.decode(System.get_env("CLOAK_KEY")), default: true}
  ]
```
