### ISSUE TITLE
Cloak.EncryptedMapField strange Poison errors

### ISSUE THREAD

**Issue by bbrock25** [danielberkompas/cloak#6]
I'm getting some strange errors when trying to convert an existing map field implementation to using the Cloak.EncryptedMapField. Is anyone else seeing this?

** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3

```elixir
     ** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
     stacktrace:
       (poison) lib/poison/encoder.ex:127: Poison.Encoder.BitString.chunk_size(<<203, 104, 48, 85, 92, 139, 139, 100, 166, 80, 183, 32, 179, 249, 92, 158, 144, 13, 144, 180, 134, 91, 72, 53, 216, 225, 52, 190, 140, 249, 133, 174, 38, 183, 96, 107, 191, 39, 15, 49, 166, 118, 87, 62, 129, 155, 77, 246, 38, 152, ...>>, nil, 2)
       (poison) lib/poison/encoder.ex:122: Poison.Encoder.BitString.escape/2
       (poison) lib/poison/encoder.ex:91: Poison.Encoder.BitString.escape/2
       (poison) lib/poison/encoder.ex:97: Poison.Encoder.BitString.escape/2
       (poison) lib/poison/encoder.ex:124: Poison.Encoder.BitString.escape/2
       (poison) lib/poison/encoder.ex:84: Poison.Encoder.BitString.encode/2
       (poison) lib/poison.ex:41: Poison.encode!/2
       (postgrex) lib/postgrex/extensions/json.ex:25: Postgrex.Extensions.JSON.encode/4
       (postgrex) lib/postgrex/query.ex:100: DBConnection.Query.Postgrex.Query.do_encode/4
       (postgrex) lib/postgrex/query.ex:61: DBConnection.Query.Postgrex.Query.encode/3
       (db_connection) lib/db_connection.ex:885: DBConnection.describe_execute/5
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
       (db_connection) lib/db_connection.ex:421: DBConnection.query/4
       (postgrex) lib/postgrex.ex:111: Postgrex.query/4
       (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
       (stdlib) timer.erl:197: :timer.tc/3
       (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.query/7
       (ecto) lib/ecto/pool.ex:149: Ecto.Pool.run/4
       (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6

```

**Comment by bbrock25** [comment]
Apparently this was due to our test db being out of sync with development. I'm good, thanks for the package!
